# Generated by Django 5.2.1 on 2025-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='time',
            field=models.CharField(choices=[('14:00', '14:00'), ('16:00', '16:00'), ('18:00', '18:00'), ('20:00', '20:00')], max_length=5),
        ),
    ]
